package request

import "time"

type StudentProfilePtkElastic struct {
	SmartbtwID                           int     `json:"smartbtw_id"`
	Name                                 string  `json:"name"`
	Photo                                string  `json:"photo"`
	SchoolName                           string  `json:"school_name"`
	SchoolID                             int     `json:"school_id"`
	MajorName                            string  `json:"major_name"`
	MajorID                              int     `json:"major_id"`
	PolbitType                           string  `json:"polbit_type"`
	PolbitCompetitionID                  *int    `json:"polbit_competition_id"`
	PolbitLocationID                     *int    `json:"polbit_location_id"`
	TargetType                           string  `json:"target_type"`
	TargetScore                          float64 `json:"target_score"`
	ModuleDone                           int     `json:"module_done"`
	TwkAvgScore                          float64 `json:"twk_avg_score"`
	TiuAvgScore                          float64 `json:"tiu_avg_score"`
	TkpAvgScore                          float64 `json:"tkp_avg_score"`
	TotalAvgScore                        float64 `json:"total_avg_score"`
	TwkAvgPercentScore                   float64 `json:"twk_avg_percent_score"`
	TiuAvgPercentScore                   float64 `json:"tiu_avg_percent_score"`
	TkpAvgPercentScore                   float64 `json:"tkp_avg_percent_score"`
	TotalAvgPercentScore                 float64 `json:"total_avg_percent_score"`
	LatestTotalScore                     float64 `json:"latest_total_score"`
	LatestTotalPercentScore              float64 `json:"latest_total_percent_score"`
	Proficiency                          string  `json:"proficiency"`
	ExamProficiency                      string  `json:"exam_proficiency"`
	StagesCompleted                      int     `json:"stages_done"`
	PassingRecommendationAvgScore        float64 `json:"passing_recommendation_avg_score"`
	PassingRecommendationAvgPercentScore float64 `json:"passing_recommendation_avg_percent_score"`
}

type StudentProfilePtnElastic struct {
	SmartbtwID                           int     `json:"smartbtw_id"`
	Name                                 string  `json:"name"`
	Photo                                string  `json:"photo"`
	SchoolID                             int     `json:"school_id"`
	SchoolName                           string  `json:"school_name"`
	MajorID                              int     `json:"major_id"`
	MajorName                            string  `json:"major_name"`
	TargetType                           string  `json:"target_type"`
	TargetScore                          float64 `json:"target_score"`
	ModuleDone                           int     `json:"module_done"`
	PkAvgScore                           float64 `json:"pk_avg_score"`
	PmAvgScore                           float64 `json:"pm_avg_score"`
	LbindAvgScore                        float64 `json:"lbind_avg_score"`
	LbingAvgScore                        float64 `json:"lbing_avg_score"`
	TotalAvgScore                        float64 `json:"total_avg_score"`
	PkAvgPercentScore                    float64 `json:"pk_avg_percent_score"`
	PmAvgPercentScore                    float64 `json:"pm_avg_percent_score"`
	LbindAvgPercentScore                 float64 `json:"lbind_avg_percent_score"`
	LbingAvgPercentScore                 float64 `json:"lbing_avg_percent_score"`
	PuAvgScore                           float64 `json:"pu_avg_score"`
	PpuAvgScore                          float64 `json:"ppu_avg_score"`
	PbmAvgScore                          float64 `json:"pbm_avg_score"`
	PuAvgPercentScore                    float64 `json:"pu_avg_percent_score"`
	PpuAvgPercentScore                   float64 `json:"ppu_avg_percent_score"`
	PbmAvgPercentScore                   float64 `json:"pbm_avg_percent_score"`
	TotalAvgPercentScore                 float64 `json:"total_avg_percent_score"`
	LatestTotalScore                     float64 `json:"latest_total_score"`
	LatestTotalPercentScore              float64 `json:"latest_total_percent_score"`
	Proficiency                          string  `json:"proficiency"`
	ExamProficiency                      string  `json:"exam_proficiency"`
	ProgramKey                           string  `json:"program_key"`
	StagesCompleted                      int     `json:"stages_done"`
	PassingRecommendationAvgScore        float64 `json:"passing_recommendation_avg_score"`
	PassingRecommendationAvgPercentScore float64 `json:"passing_recommendation_avg_percent_score"`
}

type StudentProfileElastic struct {
	SmartbtwID              int       `json:"smartbtw_id"`
	Name                    string    `json:"name"`
	Email                   string    `json:"email"`
	Phone                   string    `json:"phone"`
	Gender                  string    `json:"gender"`
	Photo                   *string   `json:"photo"`
	BranchCode              *string   `json:"branch_code"`
	BranchName              *string   `json:"branch_name"`
	BirthDate               time.Time `json:"birth_date"`
	Province                string    `json:"province"`
	ProvinceID              uint      `json:"province_id"`
	Region                  string    `json:"region"`
	RegionID                uint      `json:"region_id"`
	DomicileProvince        string    `json:"domicile_province"`
	DomicileProvinceID      uint      `json:"domicile_province_id"`
	DomicileRegion          string    `json:"domicile_region"`
	DomicileRegionID        uint      `json:"domicile_region_id"`
	LastEdID                string    `json:"last_ed_id"`
	LastEdName              string    `json:"last_ed_name"`
	LastEdType              string    `json:"last_ed_type"`
	LastEdMajor             string    `json:"last_ed_major"`
	LastEdMajorID           uint      `json:"last_ed_major_id"`
	LastEdRegion            string    `json:"last_ed_region"`
	LastEdRegionID          uint      `json:"last_ed_region_id"`
	OriginUniversity        *string   `json:"origin_university"`
	LastUniversityEdMajor   *string   `json:"last_university_ed_major"`
	LastUniversityEdMajorID *uint     `json:"last_university_ed_major_id"`
	EyeColorBlind           bool      `json:"eye_color_blind"`
	Height                  float64   `json:"height"`
	Weight                  float64   `json:"weight"`
	SchoolPTKID             uint      `json:"school_ptk_id"`
	SchoolNamePTK           string    `json:"school_name_ptk"`
	MajorNamePTK            string    `json:"major_name_ptk"`
	MajorPTKID              uint      `json:"major_ptk_id"`
	PolbitTypePTK           string    `json:"polbit_type_ptk"`
	PolbitCompetitionPTKID  uint      `json:"polbit_competition_ptk_id"`
	PolbitLocationPTKID     uint      `json:"polbit_location_ptk_id"`
	CreatedAtPTK            time.Time `json:"created_at_ptk"`
	SchoolPTNID             uint      `json:"school_ptn_id"`
	SchoolNamePTN           string    `json:"school_name_ptn"`
	MajorPTNID              uint      `json:"major_ptn_id"`
	MajorNamePTN            string    `json:"major_name_ptn"`
	CreatedAtPTN            time.Time `json:"created_at_ptn"`
	InstanceCPNSID          uint      `json:"instance_cpns_id"`
	InstanceCPNSName        string    `json:"instance_cpns_name"`
	PositionCPNSID          uint      `json:"position_cpns_id"`
	PositionCPNSName        string    `json:"position_cpns_name"`
	FormationCPNSType       string    `json:"formation_cpns_type"`
	FormationCPNSLocation   string    `json:"formation_cpns_location"`
	FormationCPNSCode       string    `json:"formation_cpns_code"`
	CompetitionCPNSID       uint      `json:"competition_cpns_id"`
	CreatedAtCPNS           time.Time `json:"created_at_cpns"`
	AccountType             string    `json:"account_type"`
	Interest                *string   `json:"interest"`
	CreatedAt               time.Time `json:"created_at"`
}
type StudentProfileUpsertElastic struct {
	SmartbtwID             int       `json:"smartbtw_id"`
	Name                   string    `json:"name"`
	Email                  string    `json:"email"`
	Phone                  string    `json:"phone"`
	Gender                 string    `json:"gender"`
	Photo                  *string   `json:"photo"`
	Province               string    `json:"province"`
	ProvinceID             uint      `json:"province_id"`
	Region                 string    `json:"region"`
	RegionID               uint      `json:"region_id"`
	DomicileProvince       string    `json:"domicile_province"`
	DomicileProvinceID     uint      `json:"domicile_province_id"`
	DomicileRegion         string    `json:"domicile_region"`
	DomicileRegionID       uint      `json:"domicile_region_id"`
	LastEdID               string    `json:"last_ed_id"`
	LastEdName             string    `json:"last_ed_name"`
	LastEdType             string    `json:"last_ed_type"`
	LastEdRegion           string    `json:"last_ed_region"`
	LastEdRegionID         uint      `json:"last_ed_region_id"`
	SchoolPTKID            uint      `json:"school_ptk_id"`
	SchoolNamePTK          string    `json:"school_name_ptk"`
	MajorNamePTK           string    `json:"major_name_ptk"`
	MajorPTKID             uint      `json:"major_ptk_id"`
	PolbitTypePTK          string    `json:"polbit_type_ptk"`
	PolbitCompetitionPTKID uint      `json:"polbit_competition_ptk_id"`
	PolbitLocationPTKID    uint      `json:"polbit_location_ptk_id"`
	CreatedAtPTK           time.Time `json:"created_at_ptk"`
	SchoolPTNID            uint      `json:"school_ptn_id"`
	SchoolNamePTN          string    `json:"school_name_ptn"`
	MajorPTNID             uint      `json:"major_ptn_id"`
	MajorNamePTN           string    `json:"major_name_ptn"`
	CreatedAtPTN           time.Time `json:"created_at_ptn"`
	InstanceCPNSID         uint      `json:"instance_cpns_id"`
	InstanceCPNSName       string    `json:"instance_cpns_name"`
	PositionCPNSID         uint      `json:"position_cpns_id"`
	PositionCPNSName       string    `json:"position_cpns_name"`
	FormationCPNSType      string    `json:"formation_cpns_type"`
	FormationCPNSLocation  string    `json:"formation_cpns_location"`
	FormationCPNSCode      string    `json:"formation_cpns_code"`
	CompetitionCPNSID      uint      `json:"competition_cpns_id"`
	CreatedAtCPNS          time.Time `json:"created_at_cpns"`
	AccountType            string    `json:"account_type"`
	BranchCode             string    `json:"branch_code"`
	BranchName             string    `json:"branch_name"`
	Interest               *string   `json:"interest"`
	OriginUniversity       *string   `json:"origin_university"`
	CreatedAt              time.Time `json:"created_at"`
}

type CreateStudentCompMapProfileElastic struct {
	SmartbtwID              int       `json:"smartbtw_id"`
	BirthDate               time.Time `json:"birth_date"`
	LastEdMajor             string    `json:"last_ed_major"`
	LastEdMajorID           uint      `json:"last_ed_major_id"`
	LastUniversityEdMajorID uint      `json:"last_university_ed_major_id"`
	LastUniversityEdMajor   string    `json:"last_university_ed_major"`
	EyeColorBlind           bool      `json:"eye_color_blind"`
	Height                  float64   `json:"height"`
	Weight                  float64   `json:"weight"`
}

type StudentProfileCPNSElastic struct {
	SmartbtwID                           int     `json:"smartbtw_id"`
	Name                                 string  `json:"name"`
	Photo                                string  `json:"photo"`
	InstanceName                         string  `json:"instance_name"`
	InstanceID                           int     `json:"instance_id"`
	PositionName                         string  `json:"position_name"`
	PositionID                           int     `json:"position_id"`
	CompetitionCpnsID                    uint    `json:"competition_id"`
	TargetType                           string  `json:"target_type"`
	TargetScore                          float64 `json:"target_score"`
	FormationType                        string  `json:"formation_type"`
	FormationCode                        string  `json:"formation_code"`
	FormationLocation                    string  `json:"formation_location"`
	ModuleDone                           int     `json:"module_done"`
	TwkAvgScore                          float64 `json:"twk_avg_score"`
	TiuAvgScore                          float64 `json:"tiu_avg_score"`
	TkpAvgScore                          float64 `json:"tkp_avg_score"`
	TotalAvgScore                        float64 `json:"total_avg_score"`
	TwkAvgPercentScore                   float64 `json:"twk_avg_percent_score"`
	TiuAvgPercentScore                   float64 `json:"tiu_avg_percent_score"`
	TkpAvgPercentScore                   float64 `json:"tkp_avg_percent_score"`
	TotalAvgPercentScore                 float64 `json:"total_avg_percent_score"`
	LatestTotalScore                     float64 `json:"latest_total_score"`
	LatestTotalPercentScore              float64 `json:"latest_total_percent_score"`
	Proficiency                          string  `json:"proficiency"`
	ExamProficiency                      string  `json:"exam_proficiency"`
	StagesCompleted                      int     `json:"stages_done"`
	PassingRecommendationAvgScore        float64 `json:"passing_recommendation_avg_score"`
	PassingRecommendationAvgPercentScore float64 `json:"passing_recommendation_avg_percent_score"`
}

type StudentProfileUKAElastic struct {
	SmartbtwID                           int     `json:"smartbtw_id"`
	Name                                 string  `json:"name"`
	Photo                                string  `json:"photo"`
	InstanceName                         string  `json:"instance_name"`
	InstanceID                           int     `json:"instance_id"`
	SchoolPTKID                          uint    `json:"school_ptk_id"`
	SchoolNamePTK                        string  `json:"school_name_ptk"`
	MajorNamePTK                         string  `json:"major_name_ptk"`
	SchoolNamePTN                        string  `json:"school_name_ptn"`
	MajorNamePTN                         string  `json:"major_name_ptn"`
	PositionName                         string  `json:"position_name"`
	PositionID                           int     `json:"position_id"`
	CompetitionCpnsID                    uint    `json:"competition_id"`
	TargetType                           string  `json:"target_type"`
	TargetScore                          float64 `json:"target_score"`
	FormationType                        string  `json:"formation_type"`
	FormationCode                        string  `json:"formation_code"`
	FormationLocation                    string  `json:"formation_location"`
	ModuleDone                           int     `json:"module_done"`
	TwkAvgScore                          float64 `json:"twk_avg_score"`
	TiuAvgScore                          float64 `json:"tiu_avg_score"`
	TkpAvgScore                          float64 `json:"tkp_avg_score"`
	TotalAvgScore                        float64 `json:"total_avg_score"`
	TwkAvgPercentScore                   float64 `json:"twk_avg_percent_score"`
	TiuAvgPercentScore                   float64 `json:"tiu_avg_percent_score"`
	TkpAvgPercentScore                   float64 `json:"tkp_avg_percent_score"`
	TotalAvgPercentScore                 float64 `json:"total_avg_percent_score"`
	LatestTotalScore                     float64 `json:"latest_total_score"`
	LatestTotalPercentScore              float64 `json:"latest_total_percent_score"`
	Proficiency                          string  `json:"proficiency"`
	ExamProficiency                      string  `json:"exam_proficiency"`
	StagesCompleted                      int     `json:"stages_done"`
	PassingRecommendationAvgScore        float64 `json:"passing_recommendation_avg_score"`
	PassingRecommendationAvgPercentScore float64 `json:"passing_recommendation_avg_percent_score"`
}
