version: "3"
networks: 
    smartbtw:
        external: true
services:
    app: 
        container_name: btw-profile-service
        image: btw-profile-service
        build: .
        env_file: 
            - .env
        networks: 
            smartbtw:
                aliases: 
                    - profile-service
